##### Practice Python

In [4]:
print(1+3)

4


In [7]:
print(range(1, 3))


range(1, 3)


In [11]:
for i in range(1, 3):
    print(i)

1
2


In [17]:
i = 3.0
print(i)
print(type(i))

3.0
<class 'float'>


In [19]:
a="a"
print(a)
print(type(a))

a
<class 'str'>


In [23]:
list = [1,2,3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


In [26]:
set1={1,2,3,4,5,4,5,5,3}
print(set1)
print(type(set1))

{1, 2, 3, 4, 5}
<class 'set'>


In [27]:
tuple1=('a','b','c')
print(tuple1)
print(type(tuple1))

('a', 'b', 'c')
<class 'tuple'>


In [28]:
tuple.add(3)

AttributeError: type object 'tuple' has no attribute 'add'

In [31]:
list.append(7)
print(list)

[1, 2, 3, 4, 7, 7]


In [32]:
with open('sample.txt','r') as file:
    content= file.read()
    print(content)

Fantastic! I'm glad to hear that a simple restart of the kernel did the trick. It's one of those surprisingly common solutions in the world of development environments.
Sometimes the environment needs a little nudge to recognize new files or changes. Happy coding, and feel free to reach out if you encounter any more hurdles!
Sometimes, Jupyter notebooks can have issues with recognizing newly created files or changes in the file system. Try restarting the kernel of your notebook. You can usually do this from the "Kernel" menu in the Jupyter interface (e.g., "Kernel" -> "Restart"). After restarting, try running the import statement again.
4. Check for Other Files Named mul.py:
It's less likely in this scenario, but sometimes there might be another file named mul.py in a different location that Python is finding instead. If you have a complex Python environment, this could potentially cause issues. However, given your description of the folder structure, this is probably not the case here

In [38]:
def file_reading():
    with open('sample.txt','r') as file:
        for line in file:
            yield line

for line in file_reading():
    print(line)



Fantastic! I'm glad to hear that a simple restart of the kernel did the trick. It's one of those surprisingly common solutions in the world of development environments.

Sometimes the environment needs a little nudge to recognize new files or changes. Happy coding, and feel free to reach out if you encounter any more hurdles!

Sometimes, Jupyter notebooks can have issues with recognizing newly created files or changes in the file system. Try restarting the kernel of your notebook. You can usually do this from the "Kernel" menu in the Jupyter interface (e.g., "Kernel" -> "Restart"). After restarting, try running the import statement again.

4. Check for Other Files Named mul.py:

It's less likely in this scenario, but sometimes there might be another file named mul.py in a different location that Python is finding instead. If you have a complex Python environment, this could potentially cause issues. However, given your description of the folder structure, this is probably not the case 

In [39]:
import os

print(os.listdir('.'))

['sample.txt', 'test.ipynb', '.git', 'practice.ipynb', 'mymodu', 'venv', 'age_based_ticket.py', 'leap_year.ipynb', 'simple_calculator.py', 'README.md', 'app.py', 'practicefile.ipynb']


In [40]:
import os 
print(os.getcwd())

/workspaces/ml_learn


In [48]:
import os
os.remove('sample1.txt')

In [66]:
a=10
b=15
c=a+b
print(a,b,c)
print(c)
name="akhil"
age = 25
print("My name is" , name , "and my age is", age)
print("my name is {} and my age is {}".format(name, age))
print(f"my name is {name} and my age is {age}")

10 15 25
25
My name is akhil and my age is 25
my name is akhil and my age is 25
my name is akhil and my age is 25


In [81]:
a=3
b=2
try:
    c =a/b
    print(c)

except Exception:
    print("Please enter b value other than zero")

finally:
    print("division successful thankyou!!!")

1.5
division successful thankyou!!!


In [3]:
str="Wow!!! I am very happy *** because today is I am very happy friday !!!!"
print(str)

str.strip('!').strip('*').strip('$')
new_str =str.replace("!","").replace("*","").split()

print(new_str)
print(type(new_str))
my_set = set(new_str)
print(my_set)

Wow!!! I am very happy *** because today is I am very happy friday !!!!
['Wow', 'I', 'am', 'very', 'happy', 'because', 'today', 'is', 'I', 'am', 'very', 'happy', 'friday']
<class 'list'>
{'Wow', 'because', 'friday', 'am', 'today', 'very', 'I', 'is', 'happy'}


In [15]:
def wrapper_file(func):
    def small_wrapper():
        print("akhil")
        func()
        print("appi")
    return small_wrapper

@wrapper_file
def new_wrapper():
    print("movate")

new_wrapper()

akhil
movate
appi


In [2]:
import numpy as np

In [29]:
arr1 = np.array([1,2,3,4,5])

In [3]:
print(arr1)

[1 2 3 4 5]


In [4]:
np.shape(arr1)

(5,)

In [8]:
np.shape(arr1)

(5,)

In [12]:
print(np.shape(arr1))

(5,)


In [13]:
type(arr1)

numpy.ndarray

In [14]:
print(arr1.shape)

(5,)


In [15]:
arr2 = np.array([1,2,3,4,5])

In [16]:
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [17]:
print(arr2.shape)

(5,)


In [18]:
print(np.shape(arr2))

(5,)


In [19]:
print(arr2)

[1 2 3 4 5]


In [20]:
print(arr2.reshape(1,5))

[[1 2 3 4 5]]


In [22]:
arr3 = ([1,2,3,4,5],[6,7,8,9,10])

In [23]:
print(arr3)

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])


In [29]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,15]])

In [30]:
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 15]]


In [31]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [41]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [45]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
arr3 = np.array([[1,2,3,4,5,6],[6,7,8,9,15,13]])
arr3.ndim

2

In [57]:
arr3.size

12

In [58]:
arr3.dtype

dtype('int64')

In [59]:
arr3.itemsize

8

In [62]:
arr4=np.array([1,2,3,4,5])
arr5=np.array([5,4,3,2,1])
arr4+arr5
arr4-arr5

array([-4, -2,  0,  2,  4])

In [63]:
arr4[4]=7

In [64]:
print(arr4)

[1 2 3 4 7]


In [67]:
arr6=np.array([[1,2,2,3,4],[2,4,5,6,7],[8,6,3,2,2]])
print(arr6)
print(arr6.ndim)
print(arr6.dtype)
print(arr6.size)
print(arr6.itemsize)

[[1 2 2 3 4]
 [2 4 5 6 7]
 [8 6 3 2 2]]
2
int64
15
8


In [85]:
print(arr6[1:,2:])

[[5 6 7]
 [3 2 2]]


In [87]:
print(arr6[1:,3:])

[[6 7]
 [2 2]]


In [91]:
print(arr6[1:,0:2])

[[2 4]
 [8 6]]


In [94]:
print(arr6[0:2,3:])

[[3 4]
 [6 7]]


In [30]:
arr1

array([1, 2, 3, 4, 5])

In [20]:
data = np.array([1,2,3,4,5,6,7,7,8,9,9,2,10,30])
mean = np.mean(data)
print(mean)
print(np.median(data))
print(np.var(data))
print(np.std(data))
print(data[data>5])
print(data[data>5] & data[data==10])

7.357142857142857
6.5
47.2295918367347
6.8723789066621395
[ 6  7  7  8  9  9 10 30]
[ 2  2  2  8  8  8 10 10]


In [21]:
import pandas as pd

In [23]:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [31]:
data1={'a':1,'b':2,'c':3}
series = pd.Series(data1)
print(series)


a    1
b    2
c    3
dtype: int64


In [32]:
data2 = [1,2,3,4,5]
index = ['a','b','c','d','e']
print(pd.Series(data, index = index))

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [34]:
data3 = {
       'name': ['akhil','akash','arun'],
       'age': [25,22,21],
       'city': ['hyd','hyd','ker']
}

In [35]:
print(data3)

{'name': ['akhil', 'akash', 'arun'], 'age': [25, 22, 21], 'city': ['hyd', 'hyd', 'ker']}


In [40]:
print(pd.DataFrame(data3))
print(type(pd.DataFrame(data3)))

    name  age city
0  akhil   25  hyd
1  akash   22  hyd
2   arun   21  ker
<class 'pandas.core.frame.DataFrame'>


In [37]:
data4= [

    {'name': 'akhil','age':25,'city':'hyd'},
    {'name': 'akash','age':22,'city':'hyd'},
    {'name': 'arun','age':21,'city':'ker'}


]

In [39]:
print(pd.DataFrame(data4))
print(type(pd.DataFrame(data4)))

    name  age city
0  akhil   25  hyd
1  akash   22  hyd
2   arun   21  ker
<class 'pandas.core.frame.DataFrame'>


In [7]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(np.mean(arr1))
print(np.std(arr1))

np.ones((3,1))

[1 2 3 4 5]
(5,)
3.0
1.4142135623730951


array([[1.],
       [1.],
       [1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)
print(arr1.itemsize)


1
int64
5
8


In [ ]:
import pandas as pd
series = pd.Series([1,23,3,4,5])  # when nothing is given then the series is considered with indexing as 0,1,2, etc
print(series)

0     1
1    23
2     3
3     4
4     5
dtype: int64


In [ ]:
series1 = pd.Series({'Name':'Akhil','Age':25,'City':'Hyd','Org':'MNC'})  #giving the dictionary data then the key is index and value is the data
print(series1)

Name    Akhil
Age        25
City      Hyd
Org       MNC
dtype: object


In [ ]:
data= ['Akhil',25,'Hyd','MNC']
index = ['Name','Age','City','Org']
series2 = pd.Series(data, index=index)   #giving seperate index values and referencing it   
print(series2)

Name    Akhil
Age        25
City      Hyd
Org       MNC
dtype: object


In [17]:
# lists of dictionary

data1 = {
    'Name': ['Akhil','Akash','Anil','Arun'],
    'Age': [25,24,23,22],
    'City': ['Hyd','Hyd','Viz','Ker']
}

df1 = pd.DataFrame(data1)
print(df1)

    Name  Age City
0  Akhil   25  Hyd
1  Akash   24  Hyd
2   Anil   23  Viz
3   Arun   22  Ker


In [19]:
# dictionaries with list

data2= [
    {'Name':'Akhil','Age':25,'City':'Hyd'},
    {'Name':'Akash','Age':24,'City':'Hyd'},
    {'Name':'Arun','Age':23,'City':'Viz'},
    {'Name':'Anil','Age':22,'City':'Ker'}

]

print(pd.DataFrame(data2))

    Name  Age City
0  Akhil   25  Hyd
1  Akash   24  Hyd
2   Arun   23  Viz
3   Anil   22  Ker


In [ ]:
with open('sample2.txt', 'r') as file:
    content = file.read()
with open('sample.csv','w') as file1:
    file1.write(content)

In [33]:
import pandas as pd
df = pd.read_csv('sample.csv', header=None)
print(df)

         0     1     2      3      4     5     6     7      8     9
0     Name   age  city     tp    day   shi   enj   shi   game   ack
1    Akhil    23   hyd    mov    sle   clo   ear   aft    vic   yes
2    Akash    34   hyd    goo    eat   sum   eve   aft    san    no
3     Anil    45   hyd    mic    pla   win   aft   nig    fre    no
4   mahesh    56   sac    ker    vin   rai   nig   mor    pub   yes
5     arun   viz   fof   danc   domc   mor   nig   pun    not   yes
6   nikhil    23   sec    ker    sle   clo   nig   aft    san    no
7     Uday    45   upl    dan    slo   win   aft   nig   sane    no
8     Ajay    33   ban    pup   play   eve   eve   eve    pub   yes
9      cha    44   blw    cat    sic   mor   nig   psu    nok    no
10    pash    77   dub    spi    oks   eve   nug   ojl   nlpo   yes


In [118]:
df.head(5)

Name   age  city     tp    day   shi   enj shi.1  game   ack
0   Akhil    23   hyd    mov    sle   clo   ear   aft   vic   yes
1   Akash    34   hyd    goo    eat   sum   eve   aft   san    no
2    Anil    45   hyd    mic    pla   win   aft   nig   fre    no
3  mahesh    56   sac    ker    vin   rai   nig   mor   pub   yes
4    arun   viz   fof   danc   domc   mor   nig   pun   not   yes

In [120]:
df.tail(6)

Name   age  city     tp    day   shi   enj shi.1   game   ack
4    arun   viz   fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23   sec    ker    sle   clo   nig   aft    san    no
6    Uday    45   upl    dan    slo   win   aft   nig   sane    no
7    Ajay    33   ban    pup   play   eve   eve   eve    pub   yes
8     cha    44   blw    cat    sic   mor   nig   psu    nok    no
9    pash    77   dub    spi    oks   eve   nug   ojl   nlpo   yes

In [119]:
df.describe()

Name  age  city    tp   day   shi   enj shi.1  game   ack
count      10   10    10    10    10    10    10    10    10    10
unique     10    8     8     9     9     6     5     7     8     2
top     Akhil   23   hyd   ker   sle   clo   nig   aft   san   yes
freq        1    2     3     2     2     2     4     3     2     5

In [58]:
df['Name']

0     Akhil
1     Akash
2      Anil
3    mahesh
4      arun
5    nikhil
6      Uday
7      Ajay
8       cha
9      pash
Name: Name, dtype: object

In [121]:
df.columns

Index(['Name', 'age', 'city', 'tp', 'day', 'shi', 'enj', 'shi.1', 'game',
       'ack'],
      dtype='object')

In [71]:
df['Name']

0     Akhil
1     Akash
2      Anil
3    mahesh
4      arun
5    nikhil
6      Uday
7      Ajay
8       cha
9      pash
Name: Name, dtype: object

In [122]:
df

Name   age  city     tp    day   shi   enj shi.1   game   ack
0   Akhil    23   hyd    mov    sle   clo   ear   aft    vic   yes
1   Akash    34   hyd    goo    eat   sum   eve   aft    san    no
2    Anil    45   hyd    mic    pla   win   aft   nig    fre    no
3  mahesh    56   sac    ker    vin   rai   nig   mor    pub   yes
4    arun   viz   fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23   sec    ker    sle   clo   nig   aft    san    no
6    Uday    45   upl    dan    slo   win   aft   nig   sane    no
7    Ajay    33   ban    pup   play   eve   eve   eve    pub   yes
8     cha    44   blw    cat    sic   mor   nig   psu    nok    no
9    pash    77   dub    spi    oks   eve   nug   ojl   nlpo   yes

In [123]:
df.loc[5]

Name     nikhil
age          23
city        sec
tp          ker
day         sle
shi         clo
enj         nig
shi.1       aft
game        san
ack          no
Name: 5, dtype: object

In [85]:
df.iloc[0]

Name      Akhil
 age         23
 city       hyd
 tp         mov
 day        sle
 shi        clo
 enj        ear
 shi.1      aft
 game       vic
 ack        yes
Name: 0, dtype: object

In [124]:
df.loc[2][8]

/tmp/ipykernel_3112/3151294202.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[2][8]


' fre'

In [93]:
df.at[1,'Name']

'Akash'

In [125]:
df.iat[1,1]

' 34'

In [97]:
df.iloc[0]

Name      Akhil
 age         23
 city       hyd
 tp         mov
 day        sle
 shi        clo
 enj        ear
 shi.1      aft
 game       vic
 ack        yes
Name: 0, dtype: object

In [ ]:
df['salary']=[25,34,2,3,4,5,5,5,34,12]  # add a new column data

In [127]:
df

Name   age  city     tp    day   shi   enj shi.1   game   ack  salary
0   Akhil    23   hyd    mov    sle   clo   ear   aft    vic   yes      25
1   Akash    34   hyd    goo    eat   sum   eve   aft    san    no      34
2    Anil    45   hyd    mic    pla   win   aft   nig    fre    no       2
3  mahesh    56   sac    ker    vin   rai   nig   mor    pub   yes       3
4    arun   viz   fof   danc   domc   mor   nig   pun    not   yes       4
5  nikhil    23   sec    ker    sle   clo   nig   aft    san    no       5
6    Uday    45   upl    dan    slo   win   aft   nig   sane    no       5
7    Ajay    33   ban    pup   play   eve   eve   eve    pub   yes       5
8     cha    44   blw    cat    sic   mor   nig   psu    nok    no      34
9    pash    77   dub    spi    oks   eve   nug   ojl   nlpo   yes      12

In [ ]:
df.drop('Name', axis=1, inplace=True)   # remove a column data, permanent operation using inplace='true' and axia=1 means column value.

In [130]:
df['Name']=['Akhil','Akash','Anil','mahesh','arun','nikhil','Uday','Ajay','cha','pash']

In [131]:
df

age  city     tp    day   shi   enj shi.1   game   ack  salary    Name
0    23   hyd    mov    sle   clo   ear   aft    vic   yes      25   Akhil
1    34   hyd    goo    eat   sum   eve   aft    san    no      34   Akash
2    45   hyd    mic    pla   win   aft   nig    fre    no       2    Anil
3    56   sac    ker    vin   rai   nig   mor    pub   yes       3  mahesh
4   viz   fof   danc   domc   mor   nig   pun    not   yes       4    arun
5    23   sec    ker    sle   clo   nig   aft    san    no       5  nikhil
6    45   upl    dan    slo   win   aft   nig   sane    no       5    Uday
7    33   ban    pup   play   eve   eve   eve    pub   yes       5    Ajay
8    44   blw    cat    sic   mor   nig   psu    nok    no      34     cha
9    77   dub    spi    oks   eve   nug   ojl   nlpo   yes      12    pash

In [137]:
df.at[1,'day']

' eat'

In [ ]:
df['game']  # removing the column data using the columnd name

0      vic
1      san
2      fre
3      pub
4      not
5      san
6     sane
7      pub
8      nok
9     nlpo
Name: game, dtype: object

In [ ]:
df.loc[5] # removing row data

age           23
city         sec
tp           ker
day          sle
shi          clo
enj          nig
shi.1        aft
game         san
ack           no
salary         5
Name      nikhil
Name: 5, dtype: object

In [140]:
df.iloc[6] # removing row data using the index location concept

age          45
city        upl
tp          dan
day         slo
shi         win
enj         aft
shi.1       nig
game       sane
ack          no
salary        5
Name       Uday
Name: 6, dtype: object

In [ ]:
df.columns  # access all columns

Index(['age', 'city', 'tp', 'day', 'shi', 'enj', 'shi.1', 'game', 'ack',
       'salary', 'Name'],
      dtype='object')

In [ ]:
df.iloc[4][5]   # accessing a specific element from the data

/tmp/ipykernel_3112/910228526.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[4][5]


' nig'

In [150]:
df.describe


<bound method NDFrame.describe of     age  city     tp    day   shi   enj shi.1   game   ack  salary    Name
0    23   hyd    mov    sle   clo   ear   aft    vic   yes      25   Akhil
1    34   hyd    goo    eat   sum   eve   aft    san    no      34   Akash
2    45   hyd    mic    pla   win   aft   nig    fre    no       2    Anil
3    56   sac    ker    vin   rai   nig   mor    pub   yes       3  mahesh
4   viz   fof   danc   domc   mor   nig   pun    not   yes       4    arun
5    23   sec    ker    sle   clo   nig   aft    san    no       5  nikhil
6    45   upl    dan    slo   win   aft   nig   sane    no       5    Uday
7    33   ban    pup   play   eve   eve   eve    pub   yes       5    Ajay
8    44   blw    cat    sic   mor   nig   psu    nok    no      34     cha
9    77   dub    spi    oks   eve   nug   ojl   nlpo   yes      12    pash>

In [169]:
# Code to check the data frame length and half of the data frame should be printed first and second half of dataframe in next.

data = {'name': 'Akhil', 'age':25, 'City': 'Hyd','Org': 'MNC'}

import pandas as pd
new_data =pd.Series(data)

print(data)
print(new_data)
length = len(new_data)
print(length)
div = int(length/2)
print('#########################')
print(new_data.iloc[0: div])
print('#########################')

print(new_data.iloc[div:])
print('#########################')


{'name': 'Akhil', 'age': 25, 'City': 'Hyd', 'Org': 'MNC'}
name    Akhil
age        25
City      Hyd
Org       MNC
dtype: object
4
#########################
name    Akhil
age        25
dtype: object
#########################
City    Hyd
Org     MNC
dtype: object
#########################


In [5]:
df


Name   age  city     tp    day   shi   enj shi.1   game   ack
0   Akhil    23   hyd    mov    sle   clo   ear   aft    vic   yes
1   Akash    34   hyd    goo    eat   sum   eve   aft    san    no
2    Anil    45   hyd    mic    pla   win   aft   nig    fre    no
3  mahesh    56   sac    ker    vin   rai   nig   mor    pub   yes
4    arun   viz   fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23   sec    ker    sle   clo   nig   aft    san    no
6    Uday    45   upl    dan    slo   win   aft   nig   sane    no
7    Ajay    33   ban    pup   play   eve   eve   eve    pub   yes
8     cha    44   blw    cat    sic   mor   nig   psu    nok    no
9    pash    77   dub    spi    oks   eve   nug   ojl   nlpo   yes

In [6]:
df.isnull()


Name    age   city     tp    day    shi    enj  shi.1   game    ack
0  False  False  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False  False  False  False
5  False  False  False  False  False  False  False  False  False  False
6  False  False  False  False  False  False  False  False  False  False
7  False  False  False  False  False  False  False  False  False  False
8  False  False  False  False  False  False  False  False  False  False
9  False  False  False  False  False  False  False  False  False  False

In [7]:
df[df.isnull()]

Name  age city   tp  day  shi  enj shi.1 game  ack
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
5  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
8  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
9  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN

In [9]:
df.isnull().any()

Name     False
age      False
city     False
tp       False
day      False
shi      False
enj      False
shi.1    False
game     False
ack      False
dtype: bool

In [4]:
import pandas as pd
df1 = pd.read_csv('sample1.csv')
print(df1)

     Name   age Unnamed: 2     tp    day   shi   enj shi.1   game   ack
0   Akhil    23        hyd    NaN    sle   clo   ear   aft    vic   yes
1   Akash    34        hyd    goo    NaN   sum   eve   aft    san    no
2    Anil    45        hyd    mic    pla   win   aft   nig    fre    no
3  mahesh    56        sac    ker    NaN   rai   nig   mor    pub   yes
4    arun   viz        fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23        sec    ker    NaN   clo   nig   aft    san    no
6    Uday    45        upl    NaN    slo   win   aft   nig   sane    no
7    Ajay    33        NaN    pup   play   eve   eve   eve    pub   yes
8     cha   NaN        blw    cat    sic   mor   nig   psu    nok    no
9    pash    77        dub    NaN    oks   eve   nug   ojl   nlpo   yes


In [24]:
df1.isnull()


Name    age  Unnamed: 2     tp    day    shi    enj  shi.1   game    ack
0  False  False       False   True  False  False  False  False  False  False
1  False  False       False  False   True  False  False  False  False  False
2  False  False       False  False  False  False  False  False  False  False
3  False  False       False  False   True  False  False  False  False  False
4  False  False       False  False  False  False  False  False  False  False
5  False  False       False  False   True  False  False  False  False  False
6  False  False       False   True  False  False  False  False  False  False
7  False  False        True  False  False  False  False  False  False  False
8  False   True       False  False  False  False  False  False  False  False
9  False  False       False   True  False  False  False  False  False  False

In [25]:
df1[df1.isnull()]

Name  age Unnamed: 2   tp  day  shi  enj shi.1 game  ack
0  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
1  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
2  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
3  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
4  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
5  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
6  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
7  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
8  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN
9  NaN  NaN        NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN

In [26]:
df1.isnull().any()

Name          False
age            True
Unnamed: 2     True
tp             True
day            True
shi           False
enj           False
shi.1         False
game          False
ack           False
dtype: bool

In [27]:
df1.isnull().sum()

Name          0
age           1
Unnamed: 2    1
tp            3
day           3
shi           0
enj           0
shi.1         0
game          0
ack           0
dtype: int64

In [7]:
df1.fillna(0)

Name   age Unnamed: 2     tp    day   shi   enj shi.1   game   ack
0   Akhil    23        hyd      0    sle   clo   ear   aft    vic   yes
1   Akash    34        hyd    goo      0   sum   eve   aft    san    no
2    Anil    45        hyd    mic    pla   win   aft   nig    fre    no
3  mahesh    56        sac    ker      0   rai   nig   mor    pub   yes
4    arun   viz        fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23        sec    ker      0   clo   nig   aft    san    no
6    Uday    45        upl      0    slo   win   aft   nig   sane    no
7    Ajay    33          0    pup   play   eve   eve   eve    pub   yes
8     cha     0        blw    cat    sic   mor   nig   psu    nok    no
9    pash    77        dub      0    oks   eve   nug   ojl   nlpo   yes

In [31]:
df1

Name   age Unnamed: 2     tp    day   shi   enj shi.1   game   ack
0   Akhil    23        hyd    NaN    sle   clo   ear   aft    vic   yes
1   Akash    34        hyd    goo    NaN   sum   eve   aft    san    no
2    Anil    45        hyd    mic    pla   win   aft   nig    fre    no
3  mahesh    56        sac    ker    NaN   rai   nig   mor    pub   yes
4    arun   viz        fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23        sec    ker    NaN   clo   nig   aft    san    no
6    Uday    45        upl    NaN    slo   win   aft   nig   sane    no
7    Ajay    33        NaN    pup   play   eve   eve   eve    pub   yes
8     cha   NaN        blw    cat    sic   mor   nig   psu    nok    no
9    pash    77        dub    NaN    oks   eve   nug   ojl   nlpo   yes

In [35]:
df1['age'] 

0      23
1      34
2      45
3      56
4     viz
5      23
6      45
7      33
8     NaN
9      77
Name: age, dtype: object

In [6]:
df1.mean()

TypeError: can only concatenate str (not "int") to str

In [38]:
df1['salary']= [100,23,43,34,35,67,67,89,89,45]


In [8]:
df1

Name   age Unnamed: 2     tp    day   shi   enj shi.1   game   ack
0   Akhil    23        hyd    NaN    sle   clo   ear   aft    vic   yes
1   Akash    34        hyd    goo    NaN   sum   eve   aft    san    no
2    Anil    45        hyd    mic    pla   win   aft   nig    fre    no
3  mahesh    56        sac    ker    NaN   rai   nig   mor    pub   yes
4    arun   viz        fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23        sec    ker    NaN   clo   nig   aft    san    no
6    Uday    45        upl    NaN    slo   win   aft   nig   sane    no
7    Ajay    33        NaN    pup   play   eve   eve   eve    pub   yes
8     cha   NaN        blw    cat    sic   mor   nig   psu    nok    no
9    pash    77        dub    NaN    oks   eve   nug   ojl   nlpo   yes

In [45]:
df3 = pd.DataFrame({'key':['A','B','C'],'value':[1,2,3]})
print(df3)
df4 = pd.DataFrame({'key':['A','B','D'],'value':[4,5,6]})
print(df4)
print('############')
pd.merge(df3, df4, on='key', how='inner' )


  key  value
0   A      1
1   B      2
2   C      3
  key  value
0   A      4
1   B      5
2   D      6
############


key  value_x  value_y
0   A        1        4
1   B        2        5

In [46]:
pd.merge(df3, df4, on='key', how='outer' )

key  value_x  value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [47]:
pd.merge(df3, df4, on='key', how='left' )

key  value_x  value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [49]:
pd.merge(df3, df4, on='key', how='right' )

key  value_x  value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6

In [51]:
pd.merge(df3, df4, on='value', how='outer' )

key_x  value key_y
0     A      1   NaN
1     B      2   NaN
2     C      3   NaN
3   NaN      4     A
4   NaN      5     B
5   NaN      6     D

In [52]:
pd.merge(df3, df4, on='key', how='left' )

key  value_x  value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [53]:
pd.merge(df3, df4, on='key', how='right' )

key  value_x  value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6

In [9]:
df1


Name   age Unnamed: 2     tp    day   shi   enj shi.1   game   ack
0   Akhil    23        hyd    NaN    sle   clo   ear   aft    vic   yes
1   Akash    34        hyd    goo    NaN   sum   eve   aft    san    no
2    Anil    45        hyd    mic    pla   win   aft   nig    fre    no
3  mahesh    56        sac    ker    NaN   rai   nig   mor    pub   yes
4    arun   viz        fof   danc   domc   mor   nig   pun    not   yes
5  nikhil    23        sec    ker    NaN   clo   nig   aft    san    no
6    Uday    45        upl    NaN    slo   win   aft   nig   sane    no
7    Ajay    33        NaN    pup   play   eve   eve   eve    pub   yes
8     cha   NaN        blw    cat    sic   mor   nig   psu    nok    no
9    pash    77        dub    NaN    oks   eve   nug   ojl   nlpo   yes

In [10]:

df5= df1.head(4)
print(df5)

     Name  age Unnamed: 2    tp   day   shi   enj shi.1  game   ack
0   Akhil   23        hyd   NaN   sle   clo   ear   aft   vic   yes
1   Akash   34        hyd   goo   NaN   sum   eve   aft   san    no
2    Anil   45        hyd   mic   pla   win   aft   nig   fre    no
3  mahesh   56        sac   ker   NaN   rai   nig   mor   pub   yes


In [11]:
df5['new_Age'] = df5['age'].astype(int)

/tmp/ipykernel_3974/3604455354.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['new_Age'] = df5['age'].astype(int)


In [12]:
df5

Name  age Unnamed: 2    tp   day   shi   enj shi.1  game   ack  new_Age
0   Akhil   23        hyd   NaN   sle   clo   ear   aft   vic   yes       23
1   Akash   34        hyd   goo   NaN   sum   eve   aft   san    no       34
2    Anil   45        hyd   mic   pla   win   aft   nig   fre    no       45
3  mahesh   56        sac   ker   NaN   rai   nig   mor   pub   yes       56

In [18]:
df5['new_Age'].std()

np.float64(14.200938936093861)

In [16]:
df5['new_Age'] = df5['new_Age']+10


/tmp/ipykernel_3974/3879891613.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['new_Age'] = df5['new_Age']+10


In [17]:
df5

Name  age Unnamed: 2    tp   day   shi   enj shi.1  game   ack  new_Age
0   Akhil   23        hyd   NaN   sle   clo   ear   aft   vic   yes       33
1   Akash   34        hyd   goo   NaN   sum   eve   aft   san    no       44
2    Anil   45        hyd   mic   pla   win   aft   nig   fre    no       55
3  mahesh   56        sac   ker   NaN   rai   nig   mor   pub   yes       66

In [19]:
df5['new_Age']=df5['new_Age'].apply(lambda x:x*5)

/tmp/ipykernel_3974/1966652202.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['new_Age']=df5['new_Age'].apply(lambda x:x*5)


In [20]:
print(df5)

     Name  age Unnamed: 2    tp   day   shi   enj shi.1  game   ack  new_Age
0   Akhil   23        hyd   NaN   sle   clo   ear   aft   vic   yes      165
1   Akash   34        hyd   goo   NaN   sum   eve   aft   san    no      220
2    Anil   45        hyd   mic   pla   win   aft   nig   fre    no      275
3  mahesh   56        sac   ker   NaN   rai   nig   mor   pub   yes      330


In [28]:
import pandas as pd
inter =pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-database/wine/wine.data')
print(inter)

HTTPError: HTTP Error 404: Not Found

In [ ]:
url = 'https://www.fdic.gov/bank-failures/failed-bank-list'
new_file = pd.read_html(url)
print(new_file)


[                               Bank Name               City         State  \
0                   Pulaski Savings Bank            Chicago      Illinois   
1     The First National Bank of Lindsay            Lindsay      Oklahoma   
2  Republic First Bank dba Republic Bank       Philadelphia  Pennsylvania   
3                          Citizens Bank           Sac City          Iowa   
4               Heartland Tri-State Bank            Elkhart        Kansas   
5                    First Republic Bank      San Francisco    California   
6                         Signature Bank           New York      New York   
7                    Silicon Valley Bank        Santa Clara    California   
8                      Almena State Bank             Almena        Kansas   
9             First City Bank of Florida  Fort Walton Beach       Florida   

    Cert                Acquiring Institution      Closing Date  \
0  28611                      Millennium Bank  January 17, 2025   
1   4134   First 

In [39]:
new_file[0]


Bank Name               City         State  \
0                   Pulaski Savings Bank            Chicago      Illinois   
1     The First National Bank of Lindsay            Lindsay      Oklahoma   
2  Republic First Bank dba Republic Bank       Philadelphia  Pennsylvania   
3                          Citizens Bank           Sac City          Iowa   
4               Heartland Tri-State Bank            Elkhart        Kansas   
5                    First Republic Bank      San Francisco    California   
6                         Signature Bank           New York      New York   
7                    Silicon Valley Bank        Santa Clara    California   
8                      Almena State Bank             Almena        Kansas   
9             First City Bank of Florida  Fort Walton Beach       Florida   

    Cert                Acquiring Institution      Closing Date  \
0  28611                      Millennium Bank  January 17, 2025   
1   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024   
2  27332    Fulton Bank, National Association    April 26, 2024   
3   8758            Iowa Trust & Savings Bank  November 3, 2023   
4  25851               Dream First Bank, N.A.     July 28, 2023   
5  59017            JPMorgan Chase Bank, N.A.       May 1, 2023   
6  57053                  Flagstar Bank, N.A.    March 12, 2023   
7  24735  First Citizens Bank & Trust Company    March 10, 2023   
8  15426                          Equity Bank  October 23, 2020   
9  16748            United Fidelity Bank, fsb  October 16, 2020   

   Fund  Sort ascending  
0                 10548  
1                 10547  
2                 10546  
3                 10545  
4                 10544  
5                 10543  
6                 10540  
7                 10539  
8                 10538  
9                 10537

In [46]:
url1="https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url1,match='country',header=0)[0]


Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [47]:
!pip install lxml